---
- name: Checking IP Address
  shell: "ifconfig | grep {{ self_host_ip }} | cut -f2 -d':' | awk 'NR==1{print $1}'"
  register: elast_network_ip

- name: Making network changes in Elastic yaml file
  replace:
    dest: '/etc/elasticsearch/elasticsearch.yml'
    regexp: '#network.host: 192.168.0.1'
    replace: 'network.host: {{ elast_network_ip.stdout }}'

- name: Adding Cluster Name
  replace:
    dest: '/etc/elasticsearch/elasticsearch.yml'
    regexp: '#cluster.name: my-application'
    replace: 'cluster.name: Anarchy'

- name: Enabling memlock in Elastic yaml file
  replace:
    dest: '/etc/elasticsearch/elasticsearch.yml'
    regexp: '#bootstrap.memory_lock: true'
    replace: 'bootstrap.memory_lock: true'

- name: Changing Node Discoveries
  replace:
    dest: '/etc/elasticsearch/elasticsearch.yml'
    regexp: '^#discovery.zen.ping.unicast.hosts: \["host1", "host2"\]'
    replace: '{{ discovery_hosts }}'

- name: Enabling Data node
  lineinfile:
    dest: '/etc/elasticsearch/elasticsearch.yml'
    line: 'node.data: true'
    state: present

- name: Disabling Master node
  lineinfile:
    dest: '/etc/elasticsearch/elasticsearch.yml'
    line: 'node.master: false'
    state: present

- name: Changing Minimum Master nodes
  replace:
    dest: '/etc/elasticsearch/elasticsearch.yml'
    regexp: '#discovery.zen.minimum_master_nodes: 3'
    replace: 'discovery.zen.minimum_master_nodes: 2'

- name: Removing all Comments
  lineinfile:
    dest: '/etc/elasticsearch/elasticsearch.yml'
    regexp: '^[#].*'
    state: absent

- name: Stopping Elasticsearch Service
  service:
    name: elasticsearch
    state: stopped

- name: Reload System Daemon to reread all config files
  systemd:
    name: elastic
    daemon_reload: yes

- name: Starting Elasticsearch Service
  service:
    name: elasticsearch
    state: started

